### ISSUE TITLE
Hammer Name

### ISSUE THREAD

**Issue by MrKrieg** [The-Bees-Decree-Server/VALKEA#10]
Hi, What is the hammer name that i can insert to a Config text such as "GizmoReloaded (to rotate any axis)"

**Comment by The-Bees-Decree-Server** [comment]
Please refer to the README of which ever version you are using, 
The hammer name is all detailed in the description of the corresponding mod on thunderstore depending on if it is VALKEA, valkeabuilds, valkeabuildsII, valkeaprops or valkeadecor.
