### ISSUE TITLE
Blocked to loading on my server

### ISSUE THREAD

**Issue by KayrozDbs** [The-Bees-Decree-Server/VALKEA#11]
Hello , i test to download valkea v2.0.0 and 2.0.1 but all version it's blocked to loading .

**Comment by The-Bees-Decree-Server** [comment]
Those versions do not support crossplay.
If you have a dedicated server just remove from server and use mod locally.
If server is local please wait for updated server sync version.

**Comment by KayrozDbs** [comment]
okay thank's
