### ISSUE TITLE
Use with Plan Build

### ISSUE THREAD

**Issue by gstrange42** [The-Bees-Decree-Server/VALKEA#14]
While it works some of the build items vanish off the bottom of the build menu. I'm not sure if there is any working mods to help?

**Comment by The-Bees-Decree-Server** [comment]
> While it works some of the build items vanish off the bottom of the build menu. I'm not sure if there is any working mods to help?

I am somewhat unfamiliar with planbuild. Though, we have used it on our server in the past without any complaints.

Perhaps reach out to the dev of PB (https://github.com/sirskunkalot/PlanBuild) and inquire there?
Or maybe a little more info/screenshots may help? Bc im not sure what menu you speak of in particular.

Also whether or not the output log shows error or warnings or any line stating, "destroying/Destroyed zdoprefab" could be helpful in troubleshooting.
