### ISSUE TITLE
Any plans to support localization?

### ISSUE THREAD

**Issue by nubihub** [The-Bees-Decree-Server/VALKEA#15]
I've tried to translate VALKEA with its prefabs on PrefabList.md file, but it's not working.
I think it's not working because I'm using Localization method for other mods that use Jotunn for dependency, but VALKEA doesn't.
Is there any other way to translate VALKEA?

**Comment by The-Bees-Decree-Server** [comment]
> I've tried to translate VALKEA with its prefabs on PrefabList.md file, but it's not working. I think it's not working because I'm using Localization method for other mods that use Jotunn for dependency, but VALKEA doesn't. Is there any other way to translate VALKEA?

Perhaps in the distant future but due to sheer number or items it would take a very longtime to accomplish this.
We will try to look into more, but it is not currently something we will be actively doing.
