### ISSUE TITLE
Any updates for multi-player

### ISSUE THREAD

**Issue by RedDust99** [The-Bees-Decree-Server/VALKEA#16]
Hello,

We'd really love to use this mod on a hosted Valheim server.  Are there any plans to get it working for multi-player?  I'm sorry if I missed something that it does actually work for multi.  Thanks!

**Comment by The-Bees-Decree-Server** [comment]
> Hello,
> 
> We'd really love to use this mod on a hosted Valheim server. Are there any plans to get it working for multi-player? I'm sorry if I missed something that it does actually work for multi. Thanks!

this version has the latest server sync and should have been fixed last version, it should be working fine for servers at this time.

**Comment by RedDust99** [comment]
Thank you that's great news.  Thanks for all the hard work.

**Comment by The-Bees-Decree-Server** [comment]
> Thank you that's great news. Thanks for all the hard work.

:)
