### ISSUE TITLE
mod

### ISSUE THREAD

**Issue by Severato** [The-Bees-Decree-Server/VALKEA#18]
with the mod [VALKEA Builds w Glass] it appears where the glass components are not all there, only the glass goods are there.
![20221224211610_1](https://user-images.githubusercontent.com/121359743/209450034-e3609f90-3942-4b08-8736-03636957debe.jpg)

**Comment by The-Bees-Decree-Server** [comment]
VALKEA BUILDS WITH GLASS enthält nur Bauteile, keine anderen Teile, Sie müssten entweder einen weiteren modularen Valkea-Mod hinzufügen oder einfach den All-in-One-VALKEA-Mod verwenden, damit alle Teile angezeigt werden.

-----

VALKEA BUILDS WITH GLASS only contains build pieces, no other pieces, you would need to either add another modular valkea mod or just use the all in one VALKEA mod for all the pieces to show.
