### ISSUE TITLE
Enhancement Request - New Asset

### ISSUE THREAD

**Issue by ValhallaCommunity** [The-Bees-Decree-Server/VALKEA#26]
Hi Bees Decree Team,

Our community would love a toilet to complete the bathroom assembly offered in the library. If prioritized, happy to sponsor and send some support!

Please let us know your thoughts!

**Comment by ValhallaCommunity** [comment]
PS don't forget the toilet paper :)

**Comment by The-Bees-Decree-Server** [comment]
Heh, funny request.
If we were to ever add such a piece it would bee more rustic and outhouse like.
But we can consider it.

**Comment by ValhallaCommunity** [comment]
1000% would want it to still maintain that Viking rustic out house feel. Thank you!!

**Comment by The-Bees-Decree-Server** [comment]
> 1000% would want it to still maintain that Viking rustic out house feel. Thank you!!

Hey mate, just wanted to let you know we added your request :)
You can find your throne with the furniture.

**Comment by ValhallaCommunity** [comment]
OMG YES THANK YOU SO MUCH THE BEES DECREE TEAM!

**Comment by The-Bees-Decree-Server** [comment]
> OMG YES THANK YOU SO MUCH THE BEES DECREE TEAM!

May you poop in peace :)
