### ISSUE TITLE
Unity Warning - Convex Mesh Inquiry

### ISSUE THREAD

**Issue by ValhallaCommunity** [The-Bees-Decree-Server/VALKEA#27]
Hi Bees Decree team,

Is Distant Dynasties triggering the two warnings? If yes, is there anything we can do?

```
[Info   :   BepInEx] Loading [DistantDynasties 1.1.0]
[Warning: Unity Log] Couldn't create a Convex Mesh from source mesh "defaultMaterial_0_0" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[Warning: Unity Log] Couldn't create a Convex Mesh from source mesh "default_132" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[Info   :   BepInEx] Loading [VALKEA 2.1.4]
```

Thank you!

**Comment by The-Bees-Decree-Server** [comment]
Those can be ignored as they are only warnings.
Due to the complex shape of some meshes this occurred on those two objects.

We wont make any promises to address it, as blender/mesh work is difficult, but we will try to keep it in mind if at all possible.

**Comment by ValhallaCommunity** [comment]
Thank you Bees Decree Team!
