### ISSUE TITLE
Sandstone walls do not block sunlight

### ISSUE THREAD

**Issue by Dshadeslayer** [The-Bees-Decree-Server/VALKEA#30]
Sunlight goes right through, as if the wall is not there to block the light.

![valheim_pvsr2fK9ZI](https://user-images.githubusercontent.com/84277183/232797395-1b59bb2b-4a94-4b38-888d-99b38f763c0a.jpg)

![valheim_v80PrKU7Wi](https://user-images.githubusercontent.com/84277183/232797427-267409d1-2706-4364-bde0-76a721bd238f.jpg)

**Comment by The-Bees-Decree-Server** [comment]
We believe this to be a shader issue, we will look into it when we have the chance.

**Comment by Dshadeslayer** [comment]
Any news on this?

**Comment by The-Bees-Decree-Server** [comment]
Sorry mate, not yet.
Our dev just had a baby, so it will be a awhile before the get back into modding.
We will let you know when we have an update.

**Comment by Dshadeslayer** [comment]
Congratulations! Hope that goes well.
