### ISSUE TITLE
Valkea 2.1.5 no longer working 

### ISSUE THREAD

**Issue by VsUK** [The-Bees-Decree-Server/VALKEA#31]
This will no longer allow the client to connect to the server after the latest update.

**Comment by RotasOpera** [comment]
I'm also unable to join a server or load into SP with Valkea enabled. It just hangs at the loading screen forever.

> [Error  : Unity Log] MissingFieldException: Field 'ZNetScene.m_instance' not found.
> Stack trace:
> ItemManager.Item.Patch_ZNetSceneAwake (ZNetScene __instance) (at <382749908de94b89a3ce462cf506d345>:0)
> (wrapper dynamic-method) ZNetScene.DMD<ZNetScene::Awake>(ZNetScene)
> [Info   : Unity Log] 06/13/2023 12:19:11: Audioman already exist, destroying self
> [Info   : Unity Log] 06/13/2023 12:19:11: Checking for installed DLCs
> [Info   : Unity Log] 06/13/2023 12:19:11: DLC:beta installed:False
> [Info   :Server Devcommands] Reloading 1 bind data.
> [Info   : Unity Log] 06/13/2023 12:19:19: Zonesystem Start 625
> [Info   : Unity Log] 06/13/2023 12:19:20: Added 3 locations, 0 vegetations, 0 environments, 0 biome env-setups, 0 clutter  from locations_cp1
> [Info   : Unity Log] 06/13/2023 12:19:20: Added 1 locations, 0 vegetations, 1 environments, 0 biome env-setups, 0 clutter  from locations_mountaincaves
> [Info   : Unity Log] 06/13/2023 12:19:20: Added 27 locations, 25 vegetations, 5 environments, 1 biome env-setups, 3 clutter  from locations_mistlands
> [Info   : Unity Log] 06/13/2023 12:19:20: DungeonDB Start 625
> [Info   : Unity Log] 06/13/2023 12:19:20: ZRpc timeout set to 30s
> [Info   : Unity Log] 06/13/2023 12:19:20: Load world: Peener (Peener)
> [Info   : Unity Log] 06/13/2023 12:19:20: Loading 141293 zdos, my sessionID: -142448598, data version: 31
> [Info   : Unity Log] 06/13/2023 12:19:20: Creating ZDOs
> [Info   : Unity Log] 06/13/2023 12:19:20: Loading in ZDOs
> [Info   : Unity Log] 06/13/2023 12:19:20: Adding to Dictionary
> [Info   : Unity Log] 06/13/2023 12:19:20: Adding to Sectors
> [Info   : Unity Log] 06/13/2023 12:19:20: Connecting Portals, Spawners & ZSyncTransforms
> [Info   : Unity Log] ConnectSpawners => Connected 13 spawners and 5 'done' spawners.
> [Info   : Unity Log] 06/13/2023 12:19:21: Loaded 9982 locations
> [Info   : Unity Log] 06/13/2023 12:19:21: Unloading unused assets
> [Info   : Unity Log] 06/13/2023 12:19:21: Starting respawn
> [Info   : Unity Log] 06/13/2023 12:19:21: Session auth respons callback
> [Info   : Unity Log] 06/13/2023 12:19:27: Unpacking compressed mapdata 8325
> [Info   : Unity Log] 06/13/2023 12:19:27: tip:$loadscreen_tip03

Any idea where I could find more helpful logfiles?

**Comment by RotasOpera** [comment]
Did you try reverting to the default_old branch in steam?

**Comment by VsUK** [comment]
> Did you try reverting to the default_old branch in steam?

I installed the server using steam cmd on a system I run a high pop Minecraft server on. I've googled & googled, but couldn't find anything on how to revert back to the previous version on a server set up with steam cmd. I know you can do it with the client but no clue if it's possible on a dedicated server.

**Comment by RotasOpera** [comment]
the flag `-beta default_old` should work

**Comment by ValhallaCommunity** [comment]
+1 issue on Valkea likely needing an update with Valheim Patch 0.216.9 release.

Issue revolves around Item Manager.

`[Error  : Unity Log] MissingFieldException: Field 'ZNetScene.m_instance' not found.
Stack trace:
(wrapper dynamic-method) ItemManager.Item.DMD<ItemManager.Item::Patch_ZNetSceneAwake>(ZNetScene)
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::Awake>(ZNetScene)`

Severity: Critical - it is one of many mods that doesn't allow a world <> player connection to be established
Likelihood: 100% repro

Error exists when mod is present.

Let me know if you need additional details @RotasOpera @The-Bees-Decree-Server. Posted similar issue on Distance Dynasties about 1 hour ago. 

Thanks for an expedited consideration!

**Comment by Samf09** [comment]
> 

Wanna confirm that this is the error I see as well when only valkea is enabled on Valheim Patch 0.216.9 release.

**Comment by OGDiamondDave** [comment]
Similar issues with my servers, logs show no errors but I cannot get into the game, just hangs at the loading screen. When I remove Valkea I was able to get in without a problem.

**Comment by The-Bees-Decree-Server** [comment]
Issue has been resolved in v2.1.6

We thank everyone for their patience.
