### ISSUE TITLE
Bogwitch Update has broke mod

### ISSUE THREAD

**Issue by arcartel** [The-Bees-Decree-Server/VALKEA#35]
Bogwitch Update has broken the mod.

**Comment by ReFleXzZ** [comment]
How? Could you explain a bit more please?

**Comment by arcartel** [comment]
Sorry have been away a few days, when I load game modded the load game screen appears but no characters to choose.

**Comment by arcartel** [comment]
Just tried again.
I get the login in with ragnar showing and when switching between characters everyone is male and naked.

**Comment by Kuhrxo** [comment]
Have exact same problem, since last update mod wont work

**Comment by arcartel** [comment]
Get to load in screen it is empty listing ragnar other characters are present yet the default male and naked.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by The-Bees-Decree-Server** [comment]
Code needs to be completely rewritten due to update. We are working on this currently but will take some time. Sorry for the inconvenience and thank you for understanding-
