### ISSUE TITLE
The mod is incompatible with the BogWitch update

### ISSUE THREAD

**Issue by parra-1998** [The-Bees-Decree-Server/VALKEA#37]
I use thunderstore to activate the mod, and when I start the game the characters appear without clothes in the selection menu and it also doesn't let me enter any world.

**Comment by vickzeinkiv** [comment]
I had a problem with that too.
After the latest Valheim update, the mod stopped working correctly.
When running in the console errors (on the screenshots).
![Screenshot 2024-11-05 013701](https://github.com/user-attachments/assets/cd55dc06-51e6-4022-8934-42132218f33e)
![Screenshot 2024-11-05 013559](https://github.com/user-attachments/assets/30e5ecb1-e951-493f-a11d-705f6bdf64ec)
![Screenshot 2024-11-05 013553](https://github.com/user-attachments/assets/2234ced7-8177-4ab9-ae17-b8addd3b1fce)


Persanage by default RAGNAROK, which indicates a glitch in the game. The other characters are naked, worlds are not loaded.

If you disable the mod, everything works.


Please fix the error

**Comment by fmatamala** [comment]
Yes, I'm having the same issue.  Please update the mod.

**Comment by The-Bees-Decree-Server** [comment]
Code needs to be completely rewritten due to update. We are working on this currently but will take some time. Sorry for the inconvenience and thank you for understanding-

**Comment by Rsslone** [comment]
Thanks for the communication. I think at this moment this is the last "Must Have" mod before we migrate our server.

**Comment by Squeech007** [comment]
thank you! looking forward to the rework of this mod XD

**Comment by The-Bees-Decree-Server** [comment]
fixed with v3.0.0 jvl version
