### ISSUE TITLE
Config file not generating

### ISSUE THREAD

**Issue by Talfereg** [The-Bees-Decree-Server/VALKEA#38]
Running this on the current version of Valheim and the mod appears to be working. 
It does not generate a CFG file on the server or on the client.
Any help would be great, thanks.

**Comment by The-Bees-Decree-Server** [comment]
> Running this on the current version of Valheim and the mod appears to be working. It does not generate a CFG file on the server or on the client. Any help would be great, thanks.

Very sorry, we need to change the readme. Now with JVL there is no config. If you need to make adjustments please use wacky'sdatabase.

**Comment by Talfereg** [comment]
ohhh okay, thanks for the quick reply!
