### ISSUE TITLE
Bookshelves Warped?

### ISSUE THREAD

**Issue by lightsourced** [The-Bees-Decree-Server/VALKEA#7]
I'm not sure if it's intended or not, but the bookshelves look like they are a bit warped. :)

screenshot: https://imgur.com/a/uMy4msa

**Comment by The-Bees-Decree-Server** [comment]
We will have the devs take a look, ty.

**Comment by The-Bees-Decree-Server** [comment]
Bookshelves are now less drunk in version 2.0.2 (VALKEA) and 1.0.1 others.
